spring.application.name=product-mdm-service

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/productdb}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:YourRootPass123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8080

# Expose Prometheus endpoint
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true